// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: messages.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ChecksumOk    bool                   `protobuf:"varint,4,opt,name=checksum_ok,json=checksumOk,proto3" json:"checksum_ok,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Message) GetChecksumOk() bool {
	if x != nil {
		return x.ChecksumOk
	}
	return false
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BatchCreateSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Ids           []int64                `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSummary) Reset() {
	*x = BatchCreateSummary{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSummary) ProtoMessage() {}

func (x *BatchCreateSummary) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSummary.ProtoReflect.Descriptor instead.
func (*BatchCreateSummary) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateSummary) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *BatchCreateSummary) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ChatNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatNote) Reset() {
	*x = ChatNote{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatNote) ProtoMessage() {}

func (x *ChatNote) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatNote.ProtoReflect.Descriptor instead.
func (*ChatNote) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ChatNote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\aotus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x14CreateMessageRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"+\n" +
	"\x13ListMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xa5\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vchecksum_ok\x18\x04 \x01(\bR\n" +
	"checksumOk\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"@\n" +
	"\x12BatchCreateSummary\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x03R\x03ids\"\x1e\n" +
	"\bChatNote\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\x93\x02\n" +
	"\x0eMessageService\x12@\n" +
	"\rCreateMessage\x12\x1d.otus.v1.CreateMessageRequest\x1a\x10.otus.v1.Message\x12@\n" +
	"\fListMessages\x12\x1c.otus.v1.ListMessagesRequest\x1a\x10.otus.v1.Message0\x01\x12K\n" +
	"\vBatchCreate\x12\x1d.otus.v1.CreateMessageRequest\x1a\x1b.otus.v1.BatchCreateSummary(\x01\x120\n" +
	"\x04Chat\x12\x11.otus.v1.ChatNote\x1a\x11.otus.v1.ChatNote(\x010\x01B.Z,github.com/evgenza/otus-app/internal/grpcapib\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messages_proto_goTypes = []any{
	(*CreateMessageRequest)(nil),  // 0: otus.v1.CreateMessageRequest
	(*ListMessagesRequest)(nil),   // 1: otus.v1.ListMessagesRequest
	(*Message)(nil),               // 2: otus.v1.Message
	(*BatchCreateSummary)(nil),    // 3: otus.v1.BatchCreateSummary
	(*ChatNote)(nil),              // 4: otus.v1.ChatNote
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_messages_proto_depIdxs = []int32{
	5, // 0: otus.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: otus.v1.MessageService.CreateMessage:input_type -> otus.v1.CreateMessageRequest
	1, // 2: otus.v1.MessageService.ListMessages:input_type -> otus.v1.ListMessagesRequest
	0, // 3: otus.v1.MessageService.BatchCreate:input_type -> otus.v1.CreateMessageRequest
	4, // 4: otus.v1.MessageService.Chat:input_type -> otus.v1.ChatNote
	2, // 5: otus.v1.MessageService.CreateMessage:output_type -> otus.v1.Message
	2, // 6: otus.v1.MessageService.ListMessages:output_type -> otus.v1.Message
	3, // 7: otus.v1.MessageService.BatchCreate:output_type -> otus.v1.BatchCreateSummary
	4, // 8: otus.v1.MessageService.Chat:output_type -> otus.v1.ChatNote
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
